#ifndef _USB_h_
#define _USB_h_
#define USB_STATE_MASK 0xf0
#define USB_SUBSTATE_MASK 0x0f
#define SUBSUBSTATE_MASK 0x000F
#define NEXT_STATE 0x0100
#define NEXT_SUBSTATE 0x0010
#define NEXT_SUBSUBSTATE 0x0001
#define SUBSUBSTATE_ERROR 0x000F
#define NO_STATE 0xFFFF
#define USB_STATE_DETACHED									0x00
#define USB_DETACHED_SUBSTATE_INITIALIZE					0x01
#define USB_DETACHED_SUBSTATE_WAIT_FOR_DEVICE				0x03
#define	USB_DETACHED_SUBSTATE_ILLEGAL						0x04
#define USB_STATE_ATTACHED										0x10
#define USB_ATTACHED_SUBSTATE_SETTLE 0x11
#define USB_ATTACHED_SUBSTATE_RESET_DEVICE						0x12
#define USB_ATTACHED_SUBSTATE_WAIT_RESET_COMPLETE				0x13
#define USB_ATTACHED_SUBSTATE_WAIT_SOF 0x14
#define USB_ATTACHED_SUBSTATE_GET_DEVICE_DESCRIPTOR_SIZE 0x15
#define USB_STATE_ADDRESSING							0x20
#define USB_STATE_CONFIGURING							0x30
#define USB_STATE_RUNNING									0x40
#define STATE_HOLDING 0x50
#define HOLDING_SUBSTATE_HOLD_INIT 0x0000
#define HOLDING_SUBSTATE_HOLD 0x0001
#define USB_STATE_ERROR							0xff
#define TSTATE_MASK 0x00F0
#define TSUBSTATE_MASK 0x000F
#define TSUBSTATE_ERROR 0x000F
#define TSTATE_IDLE 0x0000
#define TSTATE_CONTROL_NO_DATA 0x0010
#define TSUBSTATE_CONTROL_NO_DATA_SETUP 0x0000
#define TSUBSTATE_CONTROL_NO_DATA_ACK 0x0001
#define TSUBSTATE_CONTROL_NO_DATA_COMPLETE 0x0002
#define TSTATE_CONTROL_READ 0x0020
#define TSUBSTATE_CONTROL_READ_SETUP 0x0000
#define TSUBSTATE_CONTROL_READ_DATA 0x0001
#define TSUBSTATE_CONTROL_READ_ACK 0x0002
#define TSUBSTATE_CONTROL_READ_COMPLETE 0x0003
#define TSTATE_CONTROL_WRITE 0x0030
#define TSUBSTATE_CONTROL_WRITE_SETUP 0x0000
#define TSUBSTATE_CONTROL_WRITE_DATA 0x0001
#define TSUBSTATE_CONTROL_WRITE_ACK 0x0002
#define TSUBSTATE_CONTROL_WRITE_COMPLETE 0x0003
#define TSTATE_INTERRUPT_READ 0x0040
#define TSUBSTATE_INTERRUPT_READ_DATA 0x0000
#define TSUBSTATE_INTERRUPT_READ_COMPLETE 0x0001
#define TSTATE_INTERRUPT_WRITE 0x0050
#define TSUBSTATE_INTERRUPT_WRITE_DATA 0x0000
#define TSUBSTATE_INTERRUPT_WRITE_COMPLETE 0x0001
#define TSTATE_ISOCHRONOUS_READ 0x0060
#define TSUBSTATE_ISOCHRONOUS_READ_DATA 0x0000
#define TSUBSTATE_ISOCHRONOUS_READ_COMPLETE 0x0001
#define TSTATE_ISOCHRONOUS_WRITE 0x0070
#define TSUBSTATE_ISOCHRONOUS_WRITE_DATA 0x0000
#define TSUBSTATE_ISOCHRONOUS_WRITE_COMPLETE 0x0001
#define TSTATE_BULK_READ 0x0080
#define TSUBSTATE_BULK_READ_DATA 0x0000
#define TSUBSTATE_BULK_READ_COMPLETE 0x0001
#define TSTATE_BULK_WRITE 0x0090
#define TSUBSTATE_BULK_WRITE_DATA 0x0000
#define TSUBSTATE_BULK_WRITE_COMPLETE 0x0001
#define SR_GET_STATUS			0x00
#define SR_CLEAR_FEATURE		0x01
#define SR_RESERVED				0x02
#define SR_SET_FEATURE			0x03
#define SR_SET_ADDRESS			0x05
#define SR_GET_DESCRIPTOR		0x06
#define SR_SET_DESCRIPTOR		0x07
#define SR_GET_CONFIGURATION	0x08
#define SR_SET_CONFIGURATION	0x09
#define SR_GET_INTERFACE		0x0a
#define SR_SET_INTERFACE		0x0b
#define GD_DEVICE			0x01
#define GD_CONFIGURATION	0x02
#define GD_STRING			0x03
#define GD_HID	 0x21
#define GD_REPORT	 0x22
#define GET_REPORT		1
#define GET_IDLE		2
#define GET_PROTOCOL 3
#define SET_REPORT		9
#define SET_IDLE		0x0A
#define SET_PROTOCOL 0x0B
#define INPUT_REPORT 1
typedef struct _USB_MSD_DEVICE_INFO {
	BYTE blockData[31];
	BYTE deviceAddress;
	BYTE errorCode;
	BYTE state;
	BYTE returnState;
	union {
		struct {
			BYTE bfDirection :1;
			BYTE bfReset :1;
			BYTE bfClearDataIN :1;
			BYTE bfClearDataOUT :1;
		};
		BYTE val;
	} flags;
	BYTE maxLUN;
	BYTE interface;
	BYTE epin_idx;
	BYTE epout_idx;
	BYTE endpointDATA;
	BYTE *userData;
	DWORD userDataLength;
	DWORD bytesTransferred;
	DWORD dCBWTag;
	BYTE attemptsCSW;
} USB_MSD_DEVICE_INFO;
#endif
